name: Fetch planning concern data

on:
  schedule:
    - cron: '30 5 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DLB_BOT_EMAIL: ${{ secrets.DLB_BOT_EMAIL }}
  DLB_BOT_TOKEN: ${{ secrets.DLB_BOT_TOKEN }}
  DLB_BOT_USERNAME: ${{ secrets.DLB_BOT_USERNAME }}
  GOOGLE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup git
      run: |
        git config user.email "${DLB_BOT_EMAIL}"
        git config user.name "${DLB_BOT_USERNAME}"
        git remote set-url origin https://${DLB_BOT_USERNAME}:${DLB_BOT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout main

    - name: Install build dependencies
      run: make python-init

    - name: Fetch latest data
      run: make fetch-backlog-data

    - name: Output git status
      run: make status

    - name: Commit data
      run: make commit-data
